# https://rainboard.laas.fr/project/pinocchio/.gitlab-ci.yml
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: '3'

.robotpkg-py-pinocchio: &robotpkg-py-pinocchio
  retry:
    max: 2
    when: runner_system_failure
  except:
    - gh-pages
  timeout: 3 hours 30 minutes
  script:
    - export PYTHONPATH="/usr/local/lib/python3/dist-packages:$PYTHONPATH"
    - cd $CI_PROJECT_DIR
    - git clone --recursive https://github.com/stack-of-tasks/eigenpy.git
    - cd eigenpy
    - git checkout devel
    - git submodule update
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF
    - make -j3 install
    - cd ../../
    - git clone --recursive https://github.com/humanoid-path-planner/hpp-fcl.git
    - cd hpp-fcl
    - git checkout devel
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make -j3 install
    - cd ../../
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_COLLISION_SUPPORT=ON -DBUILD_WITH_SDF_SUPPORT=ON -DBUILD_ADVANCED_TESTING=OFF -DBUILD_PYTHON_BINDINGS_WITH_BOOST_MPFR_SUPPORT=OFF
      -DBUILD_WITH_CASADI_SUPPORT=OFF -DPYTHON_EXECUTABLE=$(which python3) -DBUILD_WITH_OPENMP_SUPPORT=OFF -DCMAKE_VERBOSE_MAKEFILE=False
    - make -j3 install
    - make test
  interruptible: true

robotpkg-py-pinocchio-20.04:
  <<: *robotpkg-py-pinocchio
  image: registry.gitlab.inria.fr/jucarpen/pinocchio:py-pinocchio-20.04
  allow_failure: false
